# Enter the information of the robot you want to run RelaxedIK on
loaded_robot:
  name: arm_info.yaml # please enter the name of the corresponding info file
  link_radius: 0.01 # by default
  objective_mode: noECA 
  # please type keyboard here if interactive control is desired; if you want to have
  # the robot arm follow a cartesian path, put the animation file in the 
  # animation_files folder and type the file name here
  input_device: keyboard

# scale: usually a list of three float numbers, while a single float number is sufficient for spheres
# animation: there are three options available: static, interactive and [the name of an animation file]. 
#            The option "interactive" means that you will be able to drag the obstacle around with your mouse. 
#            If you want to drive the robot with an animation file, please make sure to put the corresponding 
#            animation file in the animation_files folder
obstacles:
  cuboids:
  spheres:
  point_cloud:
