urdf_file_name: "arm.urdf"
fixed_frame: "base_link"
joint_names: [ [ "joint_1", "joint_2", "joint_3", "joint_4", "joint_5" ] ]
joint_ordering: [ "joint_5", "joint_4", "joint_3", "joint_2", "joint_1" ]
ee_fixed_joints: [ "eef" ]
starting_config: [ -0.194494168844, -1.74021098439, -1.36145918191, -0.0614192112139, -0.655138252948 ]
collision_file_name: "collision_arm.yaml"
collision_nn_file: "arm_nn"
path_to_src: "/code/src/relaxed_ik/src"
axis_types: [ [ "z", "y", "y", "y", "z" ] ]
velocity_limits: [ 0.5, 0.5, 0.5, 0.5, 0.5 ]
joint_limits: [ [-3.14,3.14], [-3.14,3.14], [-3.14,3.14], [-3.14,3.14], [-3.14,3.14],]

displacements: [ [ [0.0,0.0,0.045], [0.0,0.0,0.112], [0.0,0.0,0.11], [0.0,0.0,0.068], [0.0,0.0,0.128] ] ]
disp_offsets: [ [0.0,0.0,0.0865] ]
rot_offsets: [ [ [0.0,0.0,0.0], [0.0,0.0,0.0], [0.0,0.0,0.0], [0.0,0.0,0.0], [0.0,0.0,0.0], [0.0,0.0,0.0] ] ]
joint_types: [ [ "continuous", "continuous", "continuous", "continuous", "continuous" ] ]
joint_state_define_func_file: "arm_joint_state_define"
